# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Main Page Setup

title: Jerome Mills' Portfolio # This is what shows up in the tab of the browser

# Hero Section
name: Jerome Mills
headline: Greetings fellow space travelers!
description: >- # dont remove this line. this will ignore all new lines until the next section
  Write an awesome intro and discuss your highlights and qualification. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jpeg


# Link your resume
# You can place your resume in assets/resume/{resume.pdf or add external link such as pdf saved in google drive 
resume-url: /assets/resume/Jerome_P_Mills.pdf


# Set up external links - this will show up as small icons next to your name.

external-links:    # input only your own url slug. The icons with missing entries will not appear.
  linkedin: jeromepm    # https://www.linkedin.com/in/{your url slug} 
  github: jeromepm    # https://github.com/{your url slug} 
  stackoverflow: test      # https://stackoverflow.com/users/{your url slug}
  medium: jeromepm         # https://medium.com/@{your url slug} 
  x-twitter:   # https://x.com/{your url slug} 
  threads:            # https://threads.net/@{your url slug} 
  instragram:       # https://instagram.com/{your url slug} 
  youtube:           # https://youtube.com/@{your url slug} 
  discord:            # https://discord.com/users/{your url slug} 
  bluesky:           # https://bsky.app/profile/{your url slug} 
  

# Skills Section - Add the list of your Skills by categories/tools. The indentation for each level needs to be precise. 
skills:
  - category: Network Security and Monitoring
    tools:
    - Firewall Configuration
    - SNMP
    - Prometheus
    - Grafana
    - BIND
    - Log Collection
    - IOC Enrichement

  - category: Prototyping
    tools:
    - FDM
    - Arduino / Raspberry Pi
    - Breadboarding for circuit testing

  - category: Problem Solving / Risk Management
    tools:
    - Root Cause Analysis (e.g., 5 Whys, Fishbone Diagram)
    - DFMEA / PFMEA 
    - Six Sigma methodologies
    - Shain Red-X


# Contact Form Setup. Setup an account and copy over the key. When someone fills out the form, it will be received in your email.
formspree-key:   mblpvykn

#Certificates and Credentials
credly-certificates:
  - 261645ae-7fec-42e3-a2f6-179ebdaafe5f
  - 6f4bffe9-cd4b-4188-b024-bade6c2abc62
  - f9cd0dfb-1623-4371-be4e-d0c6c33115cf
  - 454512ae-8d03-4a9b-a25e-4d300a822814
  - 4126aa8c-729d-44ba-aa42-828ac0026cd1
  - 648df568-defa-427f-8c54-9c356c263dce

coursera-certificates:
  - 8533PRLMJSHB


# Active theme (Updatethis to switch themes). Make sure to keep the indentation the samne.
colors: # this is the basic theme
  text: "#ffffff"
  border: "#061831"
  link: "#007acc"
  highlight: "#888888"
  background: "#030A1C"
  light_background: "#11244A"


#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
